seed: 42 # pass to the dataset configs as well
device: 'cpu'
binary: True # pass to the dataset configs as well

model_name: "binary_rate_encoding_transform"

# dataset configs
dataset: "arr_beat_1s_nk"
dataset_configs:
  train_prop: 0.6
  val_prop: 0.2
  test_prop: 0.2
  balance: true
  fourier: false
  transform: true

train_batch_size: 64
eval_batch_size: 128

# logging configs
log_steps: 1

# model configs #
model_class: "TwoLayerSNN"

model_configs:
  in_dims: 360
  out_dims: 1
  recurrent_dims:
    - 120
    - 60
  out_act: "none"
  out_act_kwargs: {}
  neuron_options:
    beta: 0.9
    threshold: 1.0
    spike_grad: "atan"
    linear_options:
      learning_rule: "oja"
      learning_rate: 0.0001
      bias: true
  spike_accumulator: "sum"

# encoder configs #
encoder: "rate"
encoder_args:
  timesteps: 20

# training configs #
lr: 0.0005
optimizer: 'AdamW'

num_epochs: 10
val_steps: 1


